### ISSUE TITLE
MYST3: Lift handle moves with getting stuck in J'nanin

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1311]
[video1.zip](https://github.com/residualvm/residualvm/files/561002/video1.zip)

**Comment by bgK** [comment]
I really don't get what's wrong in this video beside the lever not going back in position all the way through. But that was fixed in #1310.

Can you explain what the bug is and what the expected behavior is?

**Comment by ctoroman** [comment]
in fact of the matter is that it is not fixed. It was, and remains)

**Comment by bgK** [comment]
This is what I get now: https://youtu.be/RH3HgL9v4ZA
Is there still something wrong?

**Comment by ctoroman** [comment]
On this video everything is OK. But i have trouble (video1.zip). Hard to explain. Language is not a native)

**Comment by bgK** [comment]
Are you sure you are using the latest daily build? I tested with today's residualvm-win32.exe, and it was working fine.

**Comment by ctoroman** [comment]
Just downloaded the latest build. All the same. :(

**Comment by ctoroman** [comment]
The version I am using is the DVD Version (MYST: 10th Anniversary DVD Edition). I'm downloaded the latest build residualvm-win32.exe (2 nov 2016). This issue is the same. 

Maybe this is discrepancy video and background?

**Comment by bgK** [comment]
I've checked some versions of the game (French CD, DVD, PAL XBox), all use the same archive file for that room. The resources seem to be fine.

**Comment by ctoroman** [comment]
This effect disappears when the modulation speed of the game settings, exposed to the full. When put to the minimum or to the middle, then it appears again
