### ISSUE TITLE
[The Longest Jouney] Can't search for info about Jacob McAllen in the archives

### ISSUE THREAD

**Issue by sombresleep** [residualvm/residualvm#1528]
Chapter 3, NPD Archives.

According to the walkthough, you must be able to get info about Jacob McAllen after reading the Church of Voltec file. But Jacob McAllen name is not clickable and therefore it never appears in the choise list (and I can't leave the room).

If I understand it correctly, this is how it should work: > search for Church of Voltec > Look at the name Jacob McAllen > search for Jacob McAllen - Continue - look at the code.

**Comment by bgK** [comment]
Can you provide more information regarding the version of the game you have, and perhaps a screenshot of the issue? Clicking on the name works fine for me:

![residualvm00013](https://user-images.githubusercontent.com/52294/54080161-29a57300-42ea-11e9-989a-752fe30b4c8d.png)

**Comment by sombresleep** [comment]
@bgK 
Game version: the latest version from GOG.com
ResidualVM version: 0.4.0git439-g5c24080e (Mar 1)

I tried to reproduce your screenshot. The name is not clickable (i examined every pixel around it):
![longest_journey_screenshot](https://user-images.githubusercontent.com/48395212/54085110-b9224480-4331-11e9-9133-4d99706b4f67.png)

[Game save file](http://sombre-sleep.com/stuff/tlj-win-011.tlj)

**Comment by bgK** [comment]
Do you have the font folder in your game datafiles? If you don't, get it from the demo version of the game and see if it fixes the issue: https://archive.org/details/Longest_Journey_demo.

**Comment by sombresleep** [comment]
It didn't help.

**Comment by bgK** [comment]
I'm a bit at a loss here. I can't reproduce the issue with your save with any of the versions of the game I have. Maybe the GOG version has something special?

Could you load your save, open the debug console using ctrl-d, and enter the `dumpLocation` command. The ResidualVM log file, located in `\users\username\Application Data\ResidualVM\Logs` should contain details about the computer terminal location. Could you please attach the file here so I can compare it with the output from other versions of the game?

**Comment by sombresleep** [comment]
I tried it on two different PCs with two different installations of the GOG version. Same result. The name is not clickable.

Are entered `dumpLocation` on the screen with terminal with the curch of Voltec page opened. Logs:
[residualvm-Terminalopened-Church.log](https://github.com/residualvm/residualvm/files/2985906/residualvm-Terminalopened-Church.log)

**Comment by joveian** [comment]
I am seeing this also with the latest gog version ("142 language update") and the same ReisdualVM version as sombresleep (Mar 1 2019 10:44:38) on Windows 10.  I noticed a couple of other things that I wanted to mention in case they might be helpful.

1) To click on the col# on the Warren Hughes page it is actually necessary to click on lines of text below that line, or in particluar a box that starts a few pixels down into the next line of text and ends a few pixels up from the bottom of the last line of test, from the beginning of the text to what looks like the rightmost pixel of any line of text (the ')' a couple of lines up, possibly a few pixels left from the end of that line).

2) On the Church of Voltec page I noticed that there are exit pixels on the screen (red cursor) below the text.  Exploring them via a low dpi mouse, it seems like a diagonal line from under the n of 'Contact:' (about what would be the middle of the next line of text there was one) down to the keyboard area of the screen where every pixel is an exit pixel, which it reaches maybe just past the N of MCALLEN.

Let me know if there is anything I could do to help.

Using the code from the guide on the 'Control Panel' still works, so it looks like this issue will not prevent progression.  So far it has been working well for me otherwise, except for audio issues at times, occasional crashes, and (maybe similar in the origional game) a few places where it is somewhat hard to find the right exit pixels (the x command helps, although sometimes the correct area isn't near the indicator). The origional game does not work well at all on Windows 10, so thanks for making ResidualVM.

**Comment by bgK** [comment]
This is now fixed.

@joveian, I'd be interested to look into the other issues you noticed. Could you create separate bug reports?

**Comment by sombresleep** [comment]
@bgK the daily build archive on the website is still not updated :(. (although the description says that it was update today)

![rvm](https://user-images.githubusercontent.com/48395212/55364336-33c92480-54d8-11e9-8ef6-54025d7c4e90.PNG)
